

var areaZero = [
    'GREAT TUSK', 'SCREAM TAIL', 'BRUTE BONNET', 'FLUTTER MANE', 'SLITHER WING', 'SANDY SHOCKS', 'IRON TREADS', 
    'IRON BUNDLE', 'IRON HANDS', 'IRON JUGULIS', 'IRON MOTH', 'IRON THORNS', 'ROARING MOON', 'IRON VALIANT'
];



module.exports = areaZero;