var blackBelt = [
    'MANKEY', 'PRIMEAPE', 'POLIWRATH', 'MACHOP', 'MACHOKE', 'MACHAMP', 'FARFETCHD', 'HITMONLEE', 'HITMONCHAN', 
    'TAUROS(paldea)', 'HERACROSS', 'TYROGUE', 'HITMONTOP', 'COMBUSKEN', 'BLAZIKEN', 'BRELOOM', 'MAKUHITA', 'HAIRYAMA', 
    'MEDITITE', 'MEDICHAM', 'MONFERNO', 'INFERNAPE', 'RIOLU', 'LUCARIO', 'CROAGUNK', 'TOXICROAK', 'GALLADE', 'PIGNITE', 
    'EMBOAR', 'TIMBURR', 'GURDURR', 'CONKELDURR', 'THROH', 'SAWK', 'SCRAGGY', 'SCRAFTY', 'MIENDOO', 'MIENSHAO', 'CHESNAUGHT', 
    'PANCHAM', 'PANGORO', 'HAWLUCHA', 'CRABRAWLER', 'CRABOMINABLE', 'STUFFUL', 'BEWEAR', 'PASSIMIAN', 'HAKAMOO', 'KOMMOO', 
    'CLOBBOPUS', 'GRAPPLOCT', 'SIRFETCHD', 'FALINKS', 'KUBFU', 'URSHIFU', 'QUAQUAVAL', 'PAWMO', 'PAWMOT', 'FLAMIGO', 'ANNIHILAPE'
];

module.exports = blackBelt;